In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [59]:
def convtiounal(image, kernal):
    output = np.zeros(np.array(image.shape) - 2)
    for x in range(1, image.shape[0] - 1):
        for y in range(1, image.shape[1] - 1):
            part_image = image[x - 1 : x + 2, y - 1 : y + 2] * kernal
            sum = np.sum(part_image)
            output[x - 1, y - 1] = sum
    return output // 9

In [60]:
class_image = cv2.imread("images/class_photo.jpg", 0)
print(class_image)
cv2.imshow("class photo", class_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
kernal = np.ones((3, 3))
print(kernal)
output = convtiounal(class_image, kernal)
print(output)
cv2.imshow("class photo", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[165 165 165 ... 148 156 151]
 [165 165 165 ... 162 153 138]
 [165 165 165 ... 128 141 159]
 ...
 [ 27  30  31 ...  33  33  33]
 [ 28  33  33 ...  32  32  32]
 [ 27  33  33 ...  31  30  30]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[165. 165. 165. ... 144. 146. 148.]
 [165. 165. 165. ... 145. 145. 145.]
 [165. 165. 165. ... 144. 143. 143.]
 ...
 [ 28.  29.  29. ...  32.  32.  32.]
 [ 29.  29.  29. ...  33.  32.  32.]
 [ 30.  31.  30. ...  32.  32.  31.]]
